# Generated by Django 4.2.4 on 2023-08-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "car_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("license_number", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(max_length=200)),
                ("car_model", models.CharField(max_length=200)),
                ("year_of_production", models.IntegerField()),
                ("odometer", models.FloatField()),
                ("in_rent", models.BooleanField()),
                ("car_cost", models.FloatField()),
                ("created_time", models.DateTimeField()),
                ("updated_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("user_phone", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=200)),
                ("middle_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("driver_license", models.CharField(max_length=200)),
                ("debt", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "deal_id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("duration_hours", models.IntegerField()),
                ("cost", models.FloatField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "car_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars_app.car"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cars_app.user"
                    ),
                ),
            ],
        ),
    ]
