# Generated by Django 4.2.4 on 2023-08-09 17:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0001_initial"),
    ]

    operations = [

    ]
