# Generated by Django 4.2.4 on 2023-08-09 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0003_alter_car_car_id_carmodel_alter_car_car_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("651de08e-deaa-49fd-99f7-22d74c19361d"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("4b5d51ed-1ed0-4053-926e-cc327b497c14"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("717dc827-cf6d-450d-85df-f1e31fb0114d"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
