# Generated by Django 4.2.4 on 2023-08-09 13:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0005_deal_status_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_status",
            field=models.CharField(
                choices=[
                    ("WAITING_CLIENT", "waiting client"),
                    ("WORKING", "working"),
                    ("RESERVED", "reserved"),
                    ("IN_THE_SERVICE", "in the service"),
                    ("UNAVAILABLE", "unavailable"),
                ],
                default="WAITING_CLIENT",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("a47f6d5d-9b13-4db5-85c3-8d01595f49f6"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("eddd81cc-c8b2-40bd-b745-2714c96c0c22"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("908344ac-556a-4396-8b29-cb88d0f96775"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
