# Generated by Django 4.2.4 on 2023-08-09 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0007_alter_car_car_id_alter_car_car_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("be0a7c6f-3b0f-4ce4-b5c5-4e3de98fb1b3"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_status",
            field=models.CharField(
                choices=[
                    ("STANDBY", "standby"),
                    ("WORKING", "working"),
                    ("RESERVED", "reserved"),
                    ("IN_THE_SERVICE", "in the service"),
                    ("UNAVAILABLE", "unavailable"),
                ],
                default="STANDBY",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("ce1c85dc-fdf6-4c82-8dd8-11fcd8758485"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("8ab6743f-7aba-436d-b454-bc5b7d6dabf9"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
