# Generated by Django 4.2.4 on 2023-08-09 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0009_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("ccfae07a-039c-42c9-acf7-06a3f85f3825"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("3824bd77-893f-46c8-b81f-af6beebc4cff"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("fdee5efd-1768-4233-b779-e4eeea5e3fa3"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
