# Generated by Django 4.2.4 on 2023-08-09 17:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0010_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarTariff",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("cost_per_hour", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("f086b901-647f-4e09-92f2-ccb11888b7a9"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_status",
            field=models.CharField(
                choices=[
                    ("STANDBY", "standby"),
                    ("RENTED", "rented"),
                    ("RESERVED", "reserved"),
                    ("IN_THE_SERVICE", "in the service"),
                    ("UNAVAILABLE", "unavailable"),
                ],
                default="STANDBY",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("56fba180-32ef-4a9e-a9a8-ceb18e55830f"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("9f1ae4bf-7738-42b7-9947-14e1c04ff545"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
