# Generated by Django 4.2.4 on 2023-08-09 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0003_cartariff_manufacturer_remove_car_in_rent_and_more"),
        ("cars_app", "0012_remove_car_in_rent_car_tariff_alter_car_car_id_and_more"),
    ]

    operations = []
