# Generated by Django 4.2.4 on 2023-08-09 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0013_merge_20230809_2026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("ba44762f-d4ee-4f1b-a39f-742e71aa1587"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("54cdd973-9224-4b75-bc59-a3c73081ec87"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("ac459e38-f17f-4376-abeb-80fe024a1c7f"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
