# Generated by Django 4.2.4 on 2023-08-09 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0014_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("59137785-f480-4f07-a5dd-e0d0157dc6d9"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("9f28c60b-4e9c-4cb6-a674-a5d84b992792"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("18728723-bd64-462e-82c0-18ba74102013"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
