# Generated by Django 4.2.4 on 2023-08-09 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0015_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("5d92636a-9144-406d-8b0b-2c4475886b01"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("f9ac08a9-57e7-46d2-8242-7a7b719e7f70"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("2ecd134e-1438-49ab-864a-fbf7c3b1271e"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
