# Generated by Django 4.2.4 on 2023-08-09 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0016_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("af583dd4-4dc7-4720-a2bc-bf302d374e1a"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("287a07ab-6487-42ef-be41-235f5276ff0d"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("6b40c683-1b15-4ec1-bc0e-df9689692150"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
