# Generated by Django 4.2.4 on 2023-08-09 17:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0018_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="tariff",
        ),
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("6fa78d28-eacc-44dd-b466-e5f82373fcb6"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("d20ee255-5934-477d-aaea-da4450866158"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("d389bcf7-33ef-4982-8f4b-cdfcc9a45e15"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.DeleteModel(
            name="CarTariff",
        ),
    ]
