# Generated by Django 4.2.4 on 2023-08-09 17:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0019_remove_car_tariff_alter_car_car_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarTariff",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("cost_per_hour", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("36095e0e-00eb-4434-b308-1b6f11287a3f"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("ac7613d9-214b-499e-a647-94169ef6a0c8"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("4ad271a0-28e6-46dc-ad9d-04e38e87d915"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
