# Generated by Django 4.2.4 on 2023-08-09 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0021_car_tariff_id_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("ec542c1e-e7cb-448d-9ebf-bfc8d59e1d95"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("58e93956-5a0e-4b5a-9bbc-0ce389bf5a70"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("caacfedb-d8a7-4366-841a-715898ef0cc0"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
