# Generated by Django 4.2.4 on 2023-08-10 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0022_remove_car_tariff_id_car_tariff_alter_car_car_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("3e7f0acf-dc68-44dc-80ea-463ef17d4796"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("261f47b7-cef4-4730-a8fd-78bcab5649df"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("50cfec23-0621-4800-b0fb-c56c32b77225"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
