# Generated by Django 4.2.4 on 2023-08-10 18:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0023_remove_car_tariff_id_alter_car_car_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("5c551fed-7096-4864-8b45-33c28a94f18f"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("7d3505a8-3bc3-49ff-9920-7407c59db412"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("9d775674-5c8d-4359-9d69-765743974547"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
