# Generated by Django 4.2.4 on 2023-08-10 18:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0024_car_tariff_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("ab6186d8-b5e1-4e4b-809a-5959a96e046d"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("225fc904-1f8a-48d0-8bf5-f42495cfca6d"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("5a4044d6-7efa-4461-8920-a582f19cd341"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
