# Generated by Django 4.2.4 on 2023-08-10 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0026_car_tariff_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="tariff",
        ),
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("858b5a22-8dfa-41b8-89d2-3016c8c4f8f5"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("2105f3b4-b652-4681-953a-74ea4faa81f1"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("10ac4474-a1af-4260-b760-591e8881b9c6"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
