# Generated by Django 4.2.4 on 2023-08-10 18:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0027_remove_car_tariff_alter_car_car_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="tariff",
            field=models.ForeignKey(
                default="default",
                on_delete=django.db.models.deletion.PROTECT,
                to="cars_app.cartariff",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("93c5db38-0a6e-459a-ac69-c16015d030cd"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("747abe72-8737-4879-b1d4-3cf5489f7e1d"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("5faab3c3-c02d-4113-b690-24fb3ba8c1d8"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
