# Generated by Django 4.2.4 on 2023-08-10 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0028_car_tariff_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("b0171261-4f6c-46b6-a68b-0fa04ede7131"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("81ef2521-ccb1-4581-9350-8e583e20e631"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("d4718c11-725a-41e2-89ed-97cf8bd86cef"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
