# Generated by Django 4.2.4 on 2023-08-10 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0029_alter_car_car_id_alter_deal_deal_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="tariff",
        ),
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("e18e41a7-3374-475e-8a38-cf73e03f33af"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("6da4b613-1cc1-477c-8b08-f9636ea26e58"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("0d8c2d7d-31e6-4bf5-9cbc-298e5531ad17"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
