# Generated by Django 4.2.4 on 2023-08-10 19:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("cars_app", "0030_remove_car_tariff_alter_car_car_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="car_tariff",
            field=models.ForeignKey(
                default="default",
                on_delete=django.db.models.deletion.PROTECT,
                to="cars_app.cartariff",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("6d3c2834-329e-4b58-8686-a3f1063e8858"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("cab544d6-e954-4801-a39a-b9c49ea58d0d"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("53f8bea8-a6dd-48db-abf4-c19c82e0486d"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
