# Generated by Django 4.2.4 on 2023-08-10 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        (
            "cars_app",
            "0031_car_car_tariff_alter_car_car_id_alter_deal_deal_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_id",
            field=models.CharField(
                default=uuid.UUID("7f403570-a930-4891-a610-bf8347a005a8"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(
                default=uuid.UUID("a2bb8c4e-2631-4feb-9d0a-b8e4ef410865"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=uuid.UUID("e5598d9b-46c0-4c13-b8e9-839fa2acfc7a"),
                max_length=200,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
